# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.NullBooleanField(choices=[(None, 'Respond (Accept/Decline)'), (True, 'Accept'), (False, 'Decline')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.NullBooleanField(choices=[(None, 'Respond (Accept/Decline)'), (True, 'Accept'), (False, 'Decline')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stall_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assoc_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.Market'),
        ),
        migrations.AddField(
            model_name='booking',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.Market'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.Stall'),
        ),
        migrations.AddField(
            model_name='application',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.Market'),
        ),
        migrations.AddField(
            model_name='application',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.Stall'),
        ),
    ]
