# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='slug',
        ),
    ]
