# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_remove_stall_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
