# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_auto_20160321_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=models.SlugField(),
        ),
    ]
