# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0008_application_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='value',
        ),
    ]
