# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
