# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0002_market_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='market',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Stall',
        ),
    ]
