# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0005_market_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='location',
        ),
        migrations.RemoveField(
            model_name='market',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='stall',
            name='market',
        ),
    ]
