# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 06:12
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0006_auto_20160214_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=Decimal('10.000000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='market',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=Decimal('10.000000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='market',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='market',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stall',
            name='market',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stally.Market'),
            preserve_default=False,
        ),
    ]
