# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='markets',
            field=models.ManyToManyField(to='stally.Market'),
        ),
    ]
