# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0011_auto_20160302_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='stally.Market'),
        ),
    ]
