# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0012_auto_20160303_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='markets',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='stally.Market'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stally.Market'),
        ),
    ]
