# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0018_auto_20160320_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stally.Market')),
                ('stalls', models.ManyToManyField(blank=True, to='stally.Stall')),
            ],
        ),
    ]
