# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0019_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stally.Market'),
        ),
    ]
