# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0020_auto_20160320_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
