# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0021_auto_20160320_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stalls',
        ),
    ]
