# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stally', '0024_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='market',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stalls',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
